[package]
name = "avocadocx-web"
version = "0.0.0"  # keep in sync
authors = [
    "Rahul Butani <r.r.butan.i+crates@gmail.com>",
    "Joseph Ryan <josephryan3.14+crates@gmail.com>"
]
edition = "2018"

description = """TODO"""
documentation = "https://docs.rs/avocadocx-web"
homepage = "https://github.com/rrbutani/avocadocx/tree/main/bin/web"
repository = "https://github.com/rrbutani/avocadocx/tree/main/bin/web"

readme = "README.md"

# TODO:
# keywords = {{{ crate keywords }}}
# categories = {{{ crate categories: https://crates.io/category_slugs }}}

license = "MIT"
# exclude = [""] # TODO

[badges]
is-it-maintained-issue-resolution = { repository = "rrbutani/avocadocx" }
is-it-maintained-open-issues = { repository = "rrbutani/avocadocx" }
maintenance = { status = "actively-developed" }

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"
log = "0.4"

abogado-common = "0.0.0"
abogado-lex = "0.0.0"
abogado-parse = "0.0.0"
# avocadocx-interpreter = "0.0.0"

chumsky = "0.3.2"
console_log = { version = "0.2", features = ["color"] }

xterm-js-sys = { version = "4.6.0-alpha1" }

[dependencies.web-sys]
version = "0.3"
features = [
  'DataTransfer',
  'DataTransferItem',
  'DataTransferItemList',
  'Document',
  'DragEvent',
  'Event',
  'Element',
  'File',
  'HtmlElement',
  'Window',
  "Location",
  "Url",
  "UrlSearchParams",
]

[package.metadata.wasm-pack.profile.dev]
wasm-opt = false

[package.metadata.wasm-pack.profile.dev.wasm-bindgen]
debug-js-glue = true
demangle-name-section = true
dwarf-debug-info = true

[package.metadata.wasm-pack.profile.release]
# The version of wasm-opt that wasm-pack bundles crashes on current wasm-bindgen
# .wasm files. Current wasm-opt (version 93) crashes on the DWARF info that
# wasm-bindgen produces. So, we'll just disable wasm-opt for now.
# wasm-opt = false #["-O4"]
wasm-opt = ["-O4"]

[package.metadata.wasm-pack.profile.release.wasm-bindgen]
debug-js-glue = false
demangle-name-section = false
dwarf-debug-info = false

[features]

[package.metadata.docs.rs]
targets = ["wasm32-unknown-unknown", "wasm32-wasi"]
rustdoc-args = ["--cfg", "docs"]
all-features = true
default-target = "wasm32-wasi"
